AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  resume challenge resources

  SAM Template for resume challenge IAM roles

Resources:
  ElasticBeanstalkRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ElasticBeanstalkEC2Role2
      Description: Role for Elastic Beanstalk IAMInstanceRole manage and deploy EC2
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument: '{
        "Version": "2012-10-17",
        "Statement": [
        {
        "Effect": "Allow",
        "Principal": {
        "AWS": "arn:aws:iam::656129116436:user/ElasticBeanstalkServiceUser",
        "Service": "ec2.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
        }]}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
      Tags:
        - Key: application
          Value: "resume challenge beanstalk"

  ElasticBeanstalkSAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ElasticBeanstalkSAMRole2
      Description: Role for Elastic Beanstalk Operations role for SAM deployment
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument: '{
        "Version": "2012-10-17",
        "Statement": [{
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
        "Service": "elasticbeanstalk.amazonaws.com"
        },
        "Action": "sts:AssumeRole",
        "Condition": {
        "StringEquals": {
        "sts:ExternalId": "elasticbeanstalk"
        }}}]}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
      Policies:
        - PolicyName: IAMPassRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action: iam:PassRole
                Resource: arn:aws:iam::656129116436:role/*
      Tags:
        - Key: application
          Value: "resume challenge beanstalk"

  ElasticBeanstalkServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ElasticBeanstalkServiceRole2
      Description: Role for Elastic Beanstalk Service Role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument: '{
        "Version": "2012-10-17",
        "Statement": [{
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
        "Service": "elasticbeanstalk.amazonaws.com"
        },
        "Action": "sts:AssumeRole",
        "Condition": {
        "StringEquals": {
        "sts:ExternalId": "elasticbeanstalk"
        }}}]}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy
      Policies:
        - PolicyName: IAMPassRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action: iam:PassRole
                Resource: arn:aws:iam::656129116436:role/*
      Tags:
        - Key: application
          Value: "resume challenge beanstalk"

  ElasticBeanstalkServiceUser:
    Type: AWS::IAM::User
    Properties:
      UserName: ElasticBeanstalkServiceUser2
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
      Tags:
        - Key: application
          Value: "resume challenge beanstalk"
