name: Deploy build folder to Amazon s3

on:
  push:
    branches: ["main"]

env:
  WORKING_DIRECTORY: react-resume

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Use the node version specified in the strategy
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2

      # Install packages
      - name: Install packages
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yarn install

      # Build an optimized production build
      - name: Production build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          unset CI
          yarn build

      # Deploy to the S3 server
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: bens-resume-challenge-benjamin1976
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./${{ env.WORKING_DIRECTORY }}/build"
